### ISSUE TITLE
Don't work with Redshift 3.0.51 (py3) 

### ISSUE THREAD

**Issue by Dragoy** [eglaubauf/egRedshiftTools#2]
An error occurs during the creation of any material:

`Traceback (most recent call last):
  File "C:/Users/<username>/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\controller.py", line 192, in execute
    self.core.create_material()
  File "C:/Users/<username>/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\core.py", line 209, in create_material
    self.material.create_material(self.cc_diffuse, self.diff_linear)
  File "C:/Users/<username>/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\eg_RSMat.py", line 90, in create_material
    self.create_layers()
  File "C:/Users/<username>/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\eg_RSMat.py", line 124, in create_layers
    self.create_displace(self.material_builder, self.redshift_material, self.files["displace"], "Displacement")
  File "C:/Users/<username>/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\eg_RSMat.py", line 182, in create_displace
    tex.parm("tex0_gammaoverride").set('1')
AttributeError: 'NoneType' object has no attribute 'set'`

**Comment by Dragoy** [comment]
I was wrong, it eventually creates the material, but it doesn't connect the displacement texture correctly

**Comment by eglaubauf** [comment]
Thanks for catching that. This should be fixed now.

**Comment by Dragoy** [comment]
Thank you for correcting that.
By the way, did you manage to adapt the plugin for the new color profile system for the new redshift?

**Comment by Dragoy** [comment]
Here is a good example of a script that assigns the correct colorspace to textures: 
https://pastebin.com/Q9trJbT1
https://pastebin.com/tr8jcQV0

**Comment by eglaubauf** [comment]
Not yet. I'll have a look, but should be a minor thing to set up. Didn't update the code for quite a while so i have to look at it again :) Thanks

**Comment by Dragoy** [comment]
> Not yet. I'll have a look, but should be a minor thing to set up. Didn't update the code for quite a while so i have to look at it again :) Thanks

Thank you so much! I would add a few more suggestions if I may. For the normal map now use a normal texture node with gamma 1 and color space linear. It would also be cool to have a checkbox to create a triplanar node for each texture node.

**Comment by eglaubauf** [comment]
Actually the Normal Map Set Up in the code needs to be changed for the Bump Node set to Normal Map Mode since it has been deprecated by the RS-Devs a while ago. Is on my Todo-List. Triplanar I'll check

**Comment by eglaubauf** [comment]
You can find the discussed changes in the dev-py3 branch now

**Comment by Dragoy** [comment]
The first time you create material, this is what happens:

`Traceback (most recent call last):
  File "C:/Users/User/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\controller.py", line 207, in execute
    self.core.create_material()
  File "C:/Users/User/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\core.py", line 217, in create_material
    self.material.create_material(self.cc_diffuse, self.diff_linear, self.triplanar)
  File "C:/Users/User/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\eg_RSMat.py", line 91, in create_material
    self.create_layers()
  File "C:/Users/User/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\eg_RSMat.py", line 131, in create_layers
    self.create_texture(self.material_builder, tri, self.files["metallic"], "Metallic", True)
  File "C:/Users/User/Documents/houdini18.5/egRedshiftTools/python3.7libs\materialBuild_RS\eg_RSMat.py", line 183, in create_texture
    connector.parm("refl_fresnel_mode").set('2')
AttributeError: 'NoneType' object has no attribute 'set'
`

**Comment by Dragoy** [comment]
He also hooked up the textures incorrectly, and placed the triplanar in the wrong place.
![image](https://user-images.githubusercontent.com/4968313/129763221-2434d2b7-167d-4857-abb6-92574bc904fb.png)

Here's a list of textures I gave him:
![image](https://user-images.githubusercontent.com/4968313/129763403-ecc64c80-8e96-4b7f-ab63-8cd9fb5c74ab.png)

**Comment by eglaubauf** [comment]
Should be fixed now

**Comment by Dragoy** [comment]
Thank you! 
Still, for some reason he does not perceive some nodes and connects them incorrectly.

Also I think it does not define different workflows Specular and Metalness. 

In this case, I chose the textures for Specular workflow:
![image](https://user-images.githubusercontent.com/4968313/129784881-179fc4f6-de28-4c87-95cf-dbcef35fb804.png)

But how he hooked them up, he mixed up some of them for some reason:
![image](https://user-images.githubusercontent.com/4968313/129785049-c82d2d3b-21e8-4071-a2af-ec25581ef78c.png)

And this is how he was supposed to place them correctly:
![image](https://user-images.githubusercontent.com/4968313/129786279-17009ecf-437f-4276-a1ec-9e8bfd2050e5.png)

**Comment by eglaubauf** [comment]
Thanks for checking again. The refl map was connecting to the wrong map. Just changed that also. Thanks

**Comment by eglaubauf** [comment]
I'll close this issue. Thanks for pointing this out again. If there is anything else please open a new one. Best, Elmar
